version: '3'

# USAGE
# docker-compose run nucypher-ci-dev python finnegans-wake-demo.py 172.29.1.3:11500

services:
  nucypher-ci-dev:
    ports:
      - 11500
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    image: ci:nucypher
    container_name: nucypher-ci-dev
    working_dir: /code/examples/
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.0
    environment:
      - FINNEGANS_WAKE_PATH=finnegans_wake_demo/finnegans-wake-excerpt.txt
  ciursula1:
    ports:
      - 11500
    image: ci:nucypher
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.1 --rest-port 11500 --lonely --disable-availability-check --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.1
    container_name: ciursula1
  ciursula2:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.2 --rest-port 11500 --disable-availability-check --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.2
    container_name: ciursula2
  ciursula3:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.3 --rest-port 11500 --disable-availability-check --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.3
    container_name: ciursula3
  ciursula4:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.4 --rest-port 11500 --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.4
    container_name: ciursula4
  ciursula5:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.5 --rest-port 11500 --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.5
    container_name: ciursula5
  ciursula6:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.6 --rest-port 11500 --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.6
    container_name: ciursula6
  ciursula7:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.7 --rest-port 11500 --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.7
    container_name: ciursula7
  ciursula8:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.8 --rest-port 11500 --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.8
    container_name: ciursula8
  ciursula9:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.9 --rest-port 11500 --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.9
    container_name: ciursula9
  ciursula10:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.10 --rest-port 11500 --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.10
    container_name: ciursula10
  ciursula11:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula1
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.11 --rest-port 11500 --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.11
    container_name: ciursula11
  ciursula12:
    ports:
      - 11500
    image: ci:nucypher
    depends_on:
      - ciursula11
    command: nucypher ursula run --dev --federated-only --rest-host 172.29.1.12 --rest-port 11500 --teacher 172.29.1.1:11500 --no-ip-checkup
    networks:
      nucypher_ci_net:
        ipv4_address: 172.29.1.12
    container_name: ciursula12

networks:
  nucypher_ci_net:
    ipam:
      driver: default
      config:
      - subnet: 172.29.1.0/16
