name: '📃 Contract Tests'

on:
  pull_request:
    branches:
      - main
      - development

concurrency:
  group: ci-tests-${{ github.ref }}-contracts
  cancel-in-progress: true

jobs:
  contract-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10 and install dependencies
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'
          cache: 'pip'  # cache pip dependencies
      - run: pip install .[dev]

      - name: Install Solidity Compiler
        run: python ./scripts/installation/install_solc.py

      - name: Run Contract tests
        run: python -m pytest tests/contracts
