name: 🧹 Darker

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  darker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - uses: akaihola/darker@1.6.1
        with:
          version: "1.6.1"
