name: 🧹 Darker

on:
  pull_request:
    branches:
      - main
      - development
      - epic-*

jobs:
  darker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - uses: akaihola/darker@1.7.2
        with:
          version: "1.7.2"
