name: 🧹 Darker

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - uses: akaihola/darker@1.5.1
        with:
          options: "--check --diff --isort"
          version: "@3c675b009d747cadd6e8048d2c57a5b1cd54fb3e"
