name: Build and Push Docker Image (version tags)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Current Version
      if: ${{ github.ref_name == 'development' }}
      run: |
        export VERSION=$(bumpversion major --dry-run --list | grep current_version= | sed 's/current_version=//g')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker-compose build --tag nucypher/nucypher:$VERSION .
        docker push nucypher/nucypher:$VERSION
