name: '🥼 Publish Lynx Experimental'

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - v*.*.*
      - epic-*

jobs:
  check-labels:
    runs-on: ubuntu-latest
    outputs:
      has-matching-label: ${{ steps.label-check.outputs.match-found }}
    steps:
      - id: label-check
        name: Check for Specific Label
        run: |
          LABEL_MATCH="Lynx" 
          MATCH_FOUND="false"
          for label in $(echo '${{ toJson(github.event.pull_request.labels.*.name) }}' | jq -r '.[]'); do
            echo "label=$label" >> $GITHUB_OUTPUT
            if [[ "$label" == "$LABEL_MATCH" ]]; then
              MATCH_FOUND="true"
              break
            fi
          done
          echo "match-found=$MATCH_FOUND" >> $GITHUB_OUTPUT
        env:
          GITHUB_OUTPUT: $GITHUB_ENV

  dispatch:
    needs: check-labels
    if: needs.check-labels.outputs.has-matching-label == 'true'
    uses: ./.github/workflows/lynx-docker.yml
    secrets: inherit
