name: '📝 Check Release Note'

on:
  pull_request:
    branches:
      - main
      - development
      - epic-*
    tags-ignore:
      - '*.*'  # ignore releases

jobs:
  release-note-entry:
    name: 'Checking release note entry for PR ${{ github.event.number }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -l ${{ github.workspace }}/newsfragments/ | grep -E '${{ github.event.number }}\.(feature|bugfix|doc|removal|misc|dev)\.rst'
