name: '🔎 Python Tests'

on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review, synchronize]

concurrency:
  group: ci-tests-${{ github.ref }}-pytest
  cancel-in-progress: true

jobs:
  python-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Install Solidity Compiler
        run: python ./scripts/installation/install_solc.py

      - name: Check Python Entrypoint
        run: python -c "import nucypher; print(nucypher.__version__)"

      - name: Unit Tests
        run: python -m pytest tests/unit

      - name: Integration Tests
        run: python -m pytest tests/integration

      - name: Agents Tests
        run: python -m pytest tests/acceptance/blockchain/agents

      - name: Actors Tests
        run: python -m pytest tests/acceptance/blockchain/actors

      - name: Deployers Tests
        run: python -m pytest tests/acceptance/blockchain/deployers

      - name: Interfaces Tests
        run: python -m pytest tests/acceptance/blockchain/interfaces

      - name: Conditions Tests
        run: python -m pytest tests/acceptance/blockchain/conditions

      - name: Characters Tests
        run: python -m pytest tests/acceptance/characters

      - name: Node Discovery Tests
        run: python -m pytest tests/acceptance/learning

      - name: Network Tests
        run: python -m pytest tests/acceptance/network

      - name: Utility Tests
        run: python -m pytest tests/acceptance/utilities

      - name: Check CLI Entrypoint
        run: nucypher --help

      - name: CLI Tests
        run: python -m pytest tests/acceptance/cli

      - name: Upload coverage report
        if: matrix.python-version == '3.10'
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
